Update firsttimepr.yml
astrolicious/studiocms pull request #262
Opened 2024-08-14 10:10 UTC by Adammatthiesen

2024-08-14 14:34 UTC, dreyfus92 approved these changes
Nice catch! LGTM ✅

2024-08-15 08:29 UTC, jdtjenkins requested changes
Other than this looks good!

2024-08-15 08:29 UTC, jdtjenkins commented on .github/workflows/firsttimepr.yml
> +                    body: `**Welcome** @${creator}, to the Contributor Squad! 🎉\n\nIf you havent already, please join our Discord, https://chat.astrolicious.dev community to stay in the loop for any
```suggestion
                    body: `**Welcome** @${creator}, to the Contributor Squad! 🎉\n\nIf you haven't already, please join our Discord, https://chat.astrolicious.dev community to stay in the loop for any future help we may need!`
```

2024-08-15 08:45 UTC, jdtjenkins approved these changes

2024-08-15 16:46 UTC, merged