Add a new `@studiocms/ui` package
astrolicious/studiocms pull request #296
Opened 2024-09-21 23:04 UTC by louisescher

#### Description
After discussing a potential dashboard redesign in #294, it was (largely) agreed upon that a new dashboard redesign would be desired. This PR aims to establish a UI library containing not only the components needed to build the new dashboard, but also add layouts to help with fonts, colors, sizes & spacings for a uniform design & better DX across the entire StudioCMS ecosystem.

2024-09-25 19:34 UTC, louisescher commented on playgrounds/ui/src/pages/double-sidebar.astro
Fixed, CSS was breaking because there was a race condition which meant that the original styles from the ui lib were overwriting my custom styles for the playground. Adding is:global to all components fixed that, although I think it's a temporary fix. Might be an issue with how Astro compiles CSS, not sure

2024-09-25 19:45 UTC, louisescher commented
Note: although comments regarding mobile & keyboard compat are appreciated, mobile & accessibility are not our focus as of now. Feel free to comment on this message with anything you find. 
Known issues:
- Keyboard nav is broken on pretty much everything that's not inputs and textboxes
- Dropdowns on mobile can overflow

2024-09-27 23:00 UTC, louisescher commented on packages/studiocms_ui/src/components/Sidebar/helpers.ts
The DoubleSidebarHelper still needs some improvements for better DX before merging

2024-09-28 06:40 UTC, Adammatthiesen approved these changes
This is going to be insane!

2024-09-28 14:32 UTC, dreyfus92 approved these changes
So far it looks good to me, we can start iterating from this point, I'm just wondering if we should add as part of the head component the `astro-capo` integration

2024-09-28 14:43 UTC, Adammatthiesen requested changes

2024-09-28 14:43 UTC, Adammatthiesen commented on packages/studiocms_ui/README.md
> +All of these components can be tested [here](https://xwwcwkcogckso80wc0ggwk4c.entropi.cc/).
```suggestion
All of these components can be tested [here](https://ui-testing.studiocms.xyz).
```

2024-09-28 15:19 UTC, louisescher commented
Known Issue: The single sidebar toggle is not visible for whatever reason in the playground

2024-10-01 17:51 UTC, ElianCodes approved these changes
Honestly, this is looking awesome! Great work team! A lot of improvements over the initial version!

You make me proud 💜 !

2024-10-01 18:08 UTC, Adammatthiesen approved these changes

2024-10-01 20:27 UTC, jdtjenkins approved these changes
https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExYWhvY3d3ZGpndWlhZnlhMXd4ZzFwMXp2Ym1ubzRxNHFud2xmMDA5ayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/fdyZ3qI0GVZC0/giphy.gif

2024-10-01 21:04 UTC, merged